### ISSUE TITLE
Stop applying the Adwaita color palette to Kirigami apps

### ISSUE THREAD

**Issue by nahuelwexd** [FedoraQt/QGnomePlatform#131] opened 2023-03-06 15:42 UTC
From a recent post by a GNOME designer[^1], it was found that QGnomePlatform would be causing black-on-black problems in Kirigami apps, due to applying the Adwaita-qt color palette indiscriminately to any Qt app.

Since according to the README, this project aims to apply GNOME settings to *unmodified* Qt apps, I suggest at least finding some way to avoid applying the Adwaita color palette on Kirigami apps.

Other parts of QGnomePlatform (like decorations) are still useful for Kirigami apps, so those should still work.

[^1]: https://mastodon.social/@tbernard/109897404484985777

**Comment by grulja** [comment] 2023-03-07 09:11
I've been trying to figure out how to identify Kirigami apps from QGnomePlatform, but I have no idea how to do that. Any idea?

**Comment by nicolasfella** [comment] 2023-03-07 12:06
Kirigami isn't strictly the problem here, it's qqc2-desktop-style (which many Kirigami apps force because there is no better style available). qqc2-desktop-style uses KColorScheme (which is kind of a superset of QPalette) to do colors. The problem here is that 1) QPalette and KColorScheme are out of sync (QGnomePlatform applies Awaita colors to QPalette but KColorScheme still uses the builting Breeze default) and 2) KColorScheme knows more color roles than QPalette

I see multiple possible solutions to this:
1) Someone creates a native Adwaita QtQuick style and QGnomePlatform applies that to apps
2) Someone creates a KColorScheme file with Adwaita colors and applies that to apps
3) Someone finds a way to "derive" a KColorScheme from a QPalette and adds that to the relevant code

**Comment by nicolasfella** [comment] 2023-03-07 12:23
Note that the problem isn't even specific to QML. Widgets apps sometimes use KColorScheme too and then have the same problem. try e.g. Kate on Gnome with a dark theme, there will be parts of the colors wrong

**Comment by nicolasfella** [comment] 2023-03-07 12:24
> Someone creates a KColorScheme file with Adwaita colors and applies that to apps

To do this create an "adwaita.colors", install it and from QGnomePlatform do `qApp->setProperty("KDE_COLOR_SCHEME_PATH", "/usr/share/color-schemes/adwaita.colors");`

**Closed** 2023-03-20 07:30 UTC
